### ISSUE TITLE
Online flow doesn't finish

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/BROWN-AESExample#2]
Hello. I imported this design using the cloud flow. I attached the relevant logs that point to the failure.
Thanks.
[cloud_error.txt](https://github.com/abdelrahmanhosny/FlowRunnerAESExample/files/3801516/cloud_error.txt)
[cloud_log.txt](https://github.com/abdelrahmanhosny/FlowRunnerAESExample/files/3801517/cloud_log.txt)
[5_1_FRlefdef.log](https://github.com/abdelrahmanhosny/FlowRunnerAESExample/files/3801518/5_1_FRlefdef.log)

**Comment by abdelrahmanhosny** [comment]
Hi @kareefardi 
Thanks a lot for your interest in the project, and many thanks for uploading these log files.

The current version of the cloud flow is based on the alpha-release of OpenROAD. There are limitations to the flow and bugs are expected. We are working on that. However, as a new version of OpenROAD is coming in January. I think the current version of the cloud flow is not going to be maintained, as a completely revamped version is under development with the new architecture of OpenROAD (using [OpenDB](https://github.com/The-OpenROAD-Project/OpenDB) as the infrastructure for the flow.

Would you like to contribute some coding/testing/documentation to any part of the project? :)
